<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rmit_rat3_hardware_interface</name>
  <version>0.0.0</version>
  <description>RAT3 ROS2 Control hardware plugin for differential drive rover</description>
  <maintainer email="s4071519@student.rmit.edu.au">Hasin</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>backward_ros</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
